[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs"]

[build.nixpacksPlan.phases.install]
cmds=["cd backend && npm install --legacy-peer-deps"]

[build.nixpacksPlan.phases.build]
cmds=["cd backend && npm run build"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
startCommand = "cd backend && npm run start"
